# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-13 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.CharField(max_length=20)),
                ('redirect', models.CharField(max_length=63)),
                ('redirectPage', models.CharField(blank=True, default='', max_length=63)),
                ('priority', models.SmallIntegerField()),
                ('tag', models.CharField(max_length=10)),
            ],
        ),
    ]
