# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_navitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='navitem',
            name='redirectPage',
            field=models.CharField(blank=True, default='', max_length=63),
        ),
    ]
