# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_auto_20160520_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('upload', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
