# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_remove_userfileupload_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='hits',
            field=models.IntegerField(default=0),
        ),
    ]
