# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0007_page_hits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='hits',
        ),
    ]
