# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-13 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0009_hitscounter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NavItem',
        ),
    ]
