# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=128)),
                ('target_date', models.DateField()),
                ('notes', models.TextField(default='')),
                ('urgency', models.NullBooleanField(choices=[(None, 'Routine'), (False, 'Priority'), (True, 'Flash')], default=None)),
                ('importance', models.NullBooleanField(choices=[(None, 'Green'), (False, 'Amber'), (True, 'Critical')], default=None)),
                ('folder', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='todo.ToDoFolder')),
                ('tags', models.ManyToManyField(to='todo.Tag')),
            ],
        ),
    ]
