# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 17:31
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160605_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='height_field',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=blog.models.upload_location, width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='post',
            name='width_field',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
